AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation stack for ExpenseTracker project

Resources:
  ExpenseTrackerS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "expense-tracker-bucket-${AWS::AccountId}"

  ExpenseTrackerDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ExpenseTracker
      AttributeDefinitions:
        - AttributeName: ExpenseID
          AttributeType: S
      KeySchema:
        - AttributeName: ExpenseID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ExpenseTrackerSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ExpenseTrackerNotifications

  ExpenseTrackerIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ExpenseTrackerLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ExpenseTrackerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: !GetAtt ExpenseTrackerDynamoDB.Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${ExpenseTrackerS3Bucket}/*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref ExpenseTrackerSNSTopic
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

Outputs:
  S3BucketName:
    Description: "S3 bucket name for storing receipts"
    Value: !Ref ExpenseTrackerS3Bucket

  DynamoDBTableName:
    Description: "DynamoDB table for storing expenses"
    Value: !Ref ExpenseTrackerDynamoDB

  SNSTopicARN:
    Description: "SNS topic for notifications"
    Value: !Ref ExpenseTrackerSNSTopic

  IAMRoleARN:
    Description: "IAM Role ARN for Lambda functions"
    Value: !GetAtt ExpenseTrackerIAMRole.Arn
