apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-backend
spec:
  selector:
    app: expense-tracker-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
