apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-backend
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0ec9c7745500b25de, subnet-05a7c5264592254db, subnet-0c4b821518b37f080, subnet-0d5aa65612896d29a, subnet-07a0d733183743174"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-05edc93d92f459066"
spec:
  selector:
    app: expense-tracker-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
