apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-frontend
  template:
    metadata:
      labels:
        app: expense-tracker-frontend
    spec:
      containers:
        - name: expense-tracker-frontend
          image: expense-tracker-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
