apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-frontend
  template:
    metadata:
      labels:
        app: expense-tracker-frontend
    spec:
      containers:
        - name: expense-tracker-frontend
          image: 897722688090.dkr.ecr.us-east-1.amazonaws.com/expense-tracker-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
