name: Django Backend CI

on:
  push:
    paths:
      - "expense-tracker-backend/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "expense-tracker-backend/**"
      - ".github/workflows/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd expense-tracker-backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     flake8 expense_tracker

      - name: Create logs directory
        run: mkdir -p expense-tracker-backend/logs

      - name: Run Django checks
        run: |
          cd expense-tracker-backend/expense_tracker
          python manage.py check

      # - name: Run tests (if you add any)
      #   run: |
      #     cd expense-tracker-backend/expense_tracker
      #     python manage.py test

      - name: Build Docker image
        run: |
          cd expense-tracker-backend
          docker build -t expense-tracker-backend:ci .

#test commit
